export enum UiActionType {
    TOGGLE_MOBILE_NAV = 'ui/TOGGLE_MOBILE_NAV',
    ADD_NOTIFICATION = 'ui/ADD_NOTIFICATION',
    REMOVE_NOTIFICATION = 'ui/REMOVE_NOTIFICATION',
    SET_DARK_MODE = 'ui/SET_DARK_MODE'
}